PROCESS = 'TRAIN'  # should be either 'TRAIN' or 'TEST'
DATASET_DIR = '../data'  # path to dataset
RESULT_DIR = '../result'  # path to result
CUDA_DEVICE = 'cuda:0'  # gpu(s) to use
NUM_WORKERS = 6  # number of workers that loads data
BATCH_SIZE = 5
MAX_EPOCH = 30
RESUME = False
SEQ_LENGTH = 3
PRE_TIME_STEP = 7
LEARNING_RATE = 0.001
MOMENTUM = 0.9
COMMENT = f"2*GAT+2*LSTM"
RESULT_SUB_FOLDER = f"{RESULT_DIR}/{COMMENT}"
CKPT_FOLDER = f"{RESULT_SUB_FOLDER}/ckpt"
CKPT_FILE = f"{CKPT_FOLDER}/ckpt.pth"
CKPT_RECORD_FOLDER = f"{CKPT_FOLDER}/record"
FROM_MEASUREMENT = "MSE"  # The measurement taken to determine the best model
SITE_ID = 1
PRINT_FEQ = 25
